package com.mycompany.dao;

import com.mycompany.model.Product;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ProductDAOTest {
    private ProductDAO productDAO;

    @BeforeEach
    void setUp() {
        productDAO = new ProductDAO();
    }

    @AfterEach
    void tearDown() {
        productDAO = null;
    }

    @Test
    public void testInsertAndSelectProduct() {
        String testName = "Test_Laptop_01";
        Product testProduct = new Product(0, testName, 5, 1200.00);

        boolean isInserted = productDAO.insertProduct(testProduct);
        assertTrue(isInserted, "Product insertion must be successful.");
        assertTrue(testProduct.getId() > 0, "Product ID must be generated by the database.");

        Product insertedProduct = productDAO.selectProductById(testProduct.getId());

        assertNotNull(insertedProduct, "The inserted product must be found by ID.");
        assertEquals(testName, insertedProduct.getName(), "Product name must match.");
        assertEquals(5, insertedProduct.getQuantity(), "Quantity must match.");
        assertEquals(1200.00, insertedProduct.getPrice(), 0.001, "Price must match.");
    }

    @Test
    public void testUpdateProduct() {
        Product productToUpdate = new Product(0, "Old_Name_Pen", 100, 1.50);
        productDAO.insertProduct(productToUpdate);
        int productId = productToUpdate.getId();

        String newName = "New_Name_Pencil";
        productToUpdate.setName(newName);

        boolean isUpdated = productDAO.updateProduct(productToUpdate);
        assertTrue(isUpdated, "Product update must be successful.");

        Product updatedProduct = productDAO.selectProductById(productId);

        assertEquals(newName, updatedProduct.getName(), "Name was not updated correctly.");
    }

    @Test
    public void testDeleteProduct() {
        Product productToDelete = new Product(0, "ToDelete_Mug", 20, 5.99);
        productDAO.insertProduct(productToDelete);
        int productId = productToDelete.getId();

        assertNotNull(productDAO.selectProductById(productId), "Product must exist before deletion test.");

        boolean isDeleted = productDAO.deleteProduct(productId);
        assertTrue(isDeleted, "Product deletion must be successful.");

        Product deletedProduct = productDAO.selectProductById(productId);
        assertNull(deletedProduct, "Product must be null after successful deletion from DB.");
    }
}